# <center>TrustRank Algorithm Implementation

### Importing the necessary Libraries

In [1]:
# importing all the necessary modules
import numpy as np
import random
import math
import operator
from collections import defaultdict

### Taking the input from the graph.txt file and converting it into an adjacency list 

In [2]:
nodes = []

# function to get dict of edges
def get_dict_of_edges(data_file):
    list_of_edges = []
    edges = defaultdict(list)

    with open (data_file, 'r') as file:
        list_of_edges = file.readlines()
    for line in list_of_edges:
        src, dst = line.split(' ')
        src, dst = int(src), int(dst[:-1])
        if src not in nodes:
            nodes.append(src)
        if dst not in nodes:
            nodes.append(dst)
        edges[src].append(dst)
    return edges

# dict_of_edges is a dict that contains the adjacency list representation
dict_of_edges = get_dict_of_edges('graph.txt')

#init the Transition matrix and the vector
T = np.zeros((len(nodes), len(nodes)))
v = np.zeros(len(nodes))


# Defining the Transition matrix
for src_node in dict_of_edges:
    length = len(dict_of_edges[src_node])
    for dst_node in dict_of_edges[src_node]:
        T[dst_node][src_node] = 1/length

### Randomly initializing 50 nodes as good and 50 nodes as bad and the rest being neutral

In [3]:
good = 50 # 50 good nodes
bad = 50 # 50 bad nodes

v = good * [1] + bad * [0] + (4039 - good - bad) * [0.5]
random.shuffle(v) # random shuffling the good and the bad nodes
v = v/np.sum(v) # normalizing the vector to have sum of elements = 1

### Inital TrustRank Score vector before starting the iteration algorithm

In [4]:
v

array([0.00024759, 0.00024759, 0.00024759, ..., 0.00024759, 0.00024759,
       0.00024759])

### As expected it should sum to 1

In [5]:
v.sum()

1.0

### Taking the damping factor as 0.85 and iterating until it converges

In [6]:
b = 0.85 # value of damping factor
temp = v 
t = v
t = b * np.dot(T,t) + (1 - b) * v
i = 1 # number of iterations

while np.linalg.norm(temp - t) > 0: # iterate till the vector converges
    temp = t
    t = b * np.dot(T,t) + (1 - b) * v
    i = i+1

print("Number of iterations to converge: {}".format(i)) # print the number of iterations

trust_rank_node_score = [] # to store the node and the corresponding trustrank score
for k in range(1, len(t)):
    if t[k] != 0:
        trust_rank_node_score.append([k, t[k]])
        
# sort the trustrank scores in the decreasing order
trust_rank_node_score = sorted(trust_rank_node_score, key = operator.itemgetter(1), reverse = True)

Number of iterations to converge: 52


### The Transition matrix

In [7]:
# Transition matrix T
T

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00288184, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00288184, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

## Final TrustRank scores for each of the nodes after convergence

In [8]:
# TrustRank scores after converging
t

array([3.71379054e-05, 3.72288772e-05, 3.72288772e-05, ...,
       5.62200711e-05, 6.04824138e-05, 1.60384518e-04])

## Node along with their TrustRank score in descending order
### Format : [Node_number , TrustRank score]

In [9]:
# node with their final TrustRank score in descending order
trust_rank_node_score

[[1911, 0.004506228203621881],
 [3434, 0.0045014754703802465],
 [2655, 0.004334743587205446],
 [1902, 0.004311051404612894],
 [1888, 0.003296892419119578],
 [2649, 0.00301173710905099],
 [1907, 0.0024445548193536733],
 [3971, 0.00242975611990265],
 [2654, 0.002358631780679669],
 [1910, 0.002000516627079585],
 [1894, 0.0018824200952636076],
 [1882, 0.0017945053529785679],
 [1898, 0.0017874812304601445],
 [3430, 0.0017815626566656578],
 [2660, 0.0017799409889277143],
 [3426, 0.0017386577192033327],
 [2642, 0.0014778362508188572],
 [332, 0.001416414806194816],
 [3422, 0.0014146230825074413],
 [1891, 0.001401696403467771],
 [2653, 0.001332147655952969],
 [3968, 0.001318967166158168],
 [1906, 0.001299455251997002],
 [1897, 0.0012895686564395874],
 [1879, 0.0012540527319210319],
 [2638, 0.0012200049905403746],
 [2659, 0.0012133033191249584],
 [2643, 0.0012039548109688074],
 [853, 0.0011810500805254302],
 [1844, 0.0011684288172122573],
 [1893, 0.001161978158629988],
 [2646, 0.0011324809582913